apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  db_host: mysql-clusterip-service
  db_port: "3306"
  db_name: netinfo-db
  db_user: root
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  db_root_password: cGFzc3dvcmQ= #password

